apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bindings-cron.action
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 1m"
    - name: route
      value: /events/action
scopes:
  - sample-app
